from enum import Enum
from app.shared.enums.entity_status import EntityStatus
from app.shared.enums.sensitivity_level import SensitivityLevel

class ModelType(str, Enum):
    LLM = "LLM"
    ML = "ML"
    CLASSIFIER = "CLASSIFIER"
    CLASSIFICATION = "CLASSIFICATION"
    EMBEDDING = "EMBEDDING"
    RULE_BASED = "RULE_BASED"
    FORECASTING = "FORECASTING"
    OPTIMIZATION = "OPTIMIZATION"
    TEST = "TEST"

class AgentType(str, Enum):
    RECOMMENDATION = "RECOMMENDATION"
    TRIAGE = "TRIAGE"
    EXTRACTION = "EXTRACTION"
    EXECUTION = "EXECUTION"
    MONITORING = "MONITORING"
    REVIEW = "REVIEW"
    ROUTING = "ROUTING"
    AUTONOMOUS = "AUTONOMOUS"
    ASSISTANT = "ASSISTANT"
    TEST = "TEST"
    OTHER = "OTHER"

class AgentExecutionMode(str, Enum):
    READ_ONLY = "READ_ONLY"
    RECOMMEND_ONLY = "RECOMMEND_ONLY"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    LIMITED_EXECUTION = "LIMITED_EXECUTION"
    BLOCKED = "BLOCKED"

class ToolCategory(str, Enum):
    ERP = "ERP"
    CRM = "CRM"
    EMAIL = "EMAIL"
    TICKETING = "TICKETING"
    DATABASE = "DATABASE"
    LLM = "LLM"
    FILE = "FILE"
    WEBHOOK = "WEBHOOK"
    GOVERNMENT = "GOVERNMENT"
    API = "API"
    SDK = "SDK"
    TEST = "TEST"
    OTHER = "OTHER"

class AccessMode(str, Enum):
    READ_ONLY = "READ_ONLY"
    WRITE = "WRITE"
    EXECUTE = "EXECUTE"
    ADMIN = "ADMIN"
    WRITE_ONLY = "WRITE_ONLY"
    READ_WRITE = "READ_WRITE"
    LIMITED = "LIMITED"
    FULL = "FULL"

class WorkflowType(str, Enum):
    ENQUIRY = "ENQUIRY"
    APPROVAL = "APPROVAL"
    CUSTOMER_SIGNAL = "CUSTOMER_SIGNAL"
    RISK_REVIEW = "RISK_REVIEW"
    OPERATIONAL_ACTION = "OPERATIONAL_ACTION"
    AI_AGENT_PIPELINE = "AI_AGENT_PIPELINE"
    ASSESSMENT = "ASSESSMENT"
    AUTOMATED = "AUTOMATED"
    SCHEDULED = "SCHEDULED"
    GOVERNANCE = "GOVERNANCE"
    INTEGRATION = "INTEGRATION"
    CUSTOM = "CUSTOM"
    TEST = "TEST"
    OTHER = "OTHER"

class SourceType(str, Enum):
    DATABASE = "DATABASE"
    API = "API"
    FILE = "FILE"
    CRM = "CRM"
    ERP = "ERP"
    DATA_LAKE = "DATA_LAKE"
    EMAIL = "EMAIL"
    WEBFORM = "WEBFORM"

class DataClassification(str, Enum):
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"
    CONFIDENTIAL = "CONFIDENTIAL"
    RESTRICTED = "RESTRICTED"

class RegistryRelationshipType(str, Enum):
    USES = "USES"
    OWNS = "OWNS"
    EXECUTES = "EXECUTES"
    APPROVES = "APPROVES"
    GOVERNED_BY = "GOVERNED_BY"
    CONNECTED_TO = "CONNECTED_TO"
    CONSUMES = "CONSUMES"
    PRODUCES = "PRODUCES"

class RegistryAuditEventType(str, Enum):
    CREATED = "CREATED"
    UPDATED = "UPDATED"
    STATUS_CHANGED = "STATUS_CHANGED"
    DELETED = "DELETED"
    RELATIONSHIP_ADDED = "RELATIONSHIP_ADDED"
    RELATIONSHIP_REMOVED = "RELATIONSHIP_REMOVED"

class EntityType(str, Enum):
    MODEL = "MODEL"
    AGENT = "AGENT"
    TOOL = "TOOL"
    WORKFLOW = "WORKFLOW"
    DATA_SOURCE = "DATA_SOURCE"
    USER = "USER"
    DEPARTMENT = "DEPARTMENT"
    ROLE = "ROLE"
