"""Add core governance entities

Revision ID: 2134b7c64f7c
Revises: d0a202de9d67
Create Date: 2026-05-22 20:28:15.935187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2134b7c64f7c'
down_revision: Union[str, Sequence[str], None] = 'd0a202de9d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass  # This migration was a placeholder and is intentionally left blank
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass  # This migration was a placeholder and is intentionally left blank
    # ### end Alembic commands ###
