"""phase1_registry_tables

Revision ID: 22192b2c0e97
Revises: 300000000000
Create Date: 2026-05-28 16:44:35.709004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22192b2c0e97'
down_revision: Union[str, Sequence[str], None] = '300000000000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registry_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('role_name', sa.String(length=150), nullable=False),
    sa.Column('role_type', sa.String(length=50), nullable=False),
    sa.Column('permissions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_code')
    )
    
    op.create_table('registry_departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_code', sa.String(length=50), nullable=False),
    sa.Column('department_name', sa.String(length=150), nullable=False),
    sa.Column('parent_department_id', sa.UUID(), nullable=True),
    sa.Column('business_owner_user_id', sa.UUID(), nullable=True),
    sa.Column('escalation_owner_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_department_id'], ['registry_departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_code')
    )

    op.create_table('guardian_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('approval_limit_level', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['registry_departments.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['registry_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    
    op.create_table('registry_audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('registry_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_entity_type', sa.String(length=80), nullable=False),
    sa.Column('source_entity_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=80), nullable=False),
    sa.Column('target_entity_type', sa.String(length=80), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('registry_ai_agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_code', sa.String(length=80), nullable=False),
    sa.Column('agent_name', sa.String(length=200), nullable=False),
    sa.Column('agent_type', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('execution_mode', sa.String(length=80), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('confidence_threshold', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('capabilities_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['registry_departments.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['guardian_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_code')
    )
    
    op.create_table('registry_ai_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_code', sa.String(length=80), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('model_type', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('version', sa.String(length=80), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('deployment_environment', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['registry_departments.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['guardian_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_code')
    )
    
    op.create_table('registry_data_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_code', sa.String(length=80), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('classification', sa.String(length=80), nullable=False),
    sa.Column('sensitivity_level', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('contains_pii', sa.Boolean(), nullable=True),
    sa.Column('retention_policy', sa.String(length=200), nullable=True),
    sa.Column('connection_reference', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['registry_departments.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['guardian_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_code')
    )
    
    op.create_table('registry_tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_code', sa.String(length=80), nullable=False),
    sa.Column('tool_name', sa.String(length=200), nullable=False),
    sa.Column('tool_category', sa.String(length=80), nullable=False),
    sa.Column('access_mode', sa.String(length=80), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('sensitivity_level', sa.String(length=50), nullable=False),
    sa.Column('allowed_operations_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('endpoint_reference', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['guardian_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_code')
    )
    
    op.create_table('registry_workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_code', sa.String(length=80), nullable=False),
    sa.Column('workflow_name', sa.String(length=200), nullable=False),
    sa.Column('workflow_type', sa.String(length=80), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=True),
    sa.Column('business_criticality', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('steps_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['registry_departments.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['guardian_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_code')
    )
    
    # Add the foreign keys for registry_departments that point to guardian_users
    op.create_foreign_key('fk_reg_dept_biz_owner', 'registry_departments', 'guardian_users', ['business_owner_user_id'], ['id'])
    op.create_foreign_key('fk_reg_dept_esc_owner', 'registry_departments', 'guardian_users', ['escalation_owner_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_reg_dept_biz_owner', 'registry_departments', type_='foreignkey')
    op.drop_constraint('fk_reg_dept_esc_owner', 'registry_departments', type_='foreignkey')
    
    op.drop_table('registry_workflows')
    op.drop_table('registry_tools')
    op.drop_table('registry_data_sources')
    op.drop_table('registry_ai_models')
    op.drop_table('registry_ai_agents')
    op.drop_table('guardian_users')
    op.drop_table('registry_departments')
    op.drop_table('registry_roles')
    op.drop_table('registry_relationships')
    op.drop_table('registry_audit_events')
    # ### end Alembic commands ###
