"""Add AI Model Providers

Revision ID: 97345b582a8c
Revises: 5541617e8f6c
Create Date: 2026-06-03 23:43:35.713184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97345b582a8c'
down_revision: Union[str, Sequence[str], None] = '5541617e8f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registry_ai_model_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.String(length=80), nullable=False),
    sa.Column('provider_name', sa.String(length=200), nullable=False),
    sa.Column('provider_category', sa.String(length=80), nullable=True),
    sa.Column('ownership_type', sa.String(length=80), nullable=True),
    sa.Column('hosting_type', sa.String(length=80), nullable=True),
    sa.Column('data_residency', sa.String(length=80), nullable=True),
    sa.Column('risk_classification', sa.String(length=50), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('registry_ai_models', sa.Column('provider_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'registry_ai_models', 'registry_ai_model_providers', ['provider_id'], ['id'])
    op.drop_column('registry_ai_models', 'provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registry_ai_models', sa.Column('provider', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'registry_ai_models', type_='foreignkey')
    op.drop_column('registry_ai_models', 'provider_id')
    op.drop_table('registry_ai_model_providers')
    # ### end Alembic commands ###
