"""Add core governance entities

Revision ID: d0a202de9d67
Revises: 4116e4746a54
Create Date: 2026-05-22 15:26:14.663014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a202de9d67'
down_revision: Union[str, Sequence[str], None] = '4116e4746a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('reference_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_policies_reference_id'), 'policies', ['reference_id'], unique=False)
    op.create_index(op.f('ix_policies_status'), 'policies', ['status'], unique=False)
    op.create_index(op.f('ix_ai_models_status'), 'ai_models', ['status'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    connection = op.get_bind()
    
    # Helper to check if index exists
    for index_name, table in [
        ('ix_audit_events_created_at', 'audit_events'),
        ('ix_recommendations_status', 'recommendations'),
        ('ix_ai_models_status', 'ai_models'),
        ('ix_policies_status', 'policies'),
        ('ix_policies_reference_id', 'policies')
    ]:
        check_index = connection.execute(sa.text(
            "SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace "
            "WHERE c.relname = :name AND c.relkind = 'i'"
        ), {"name": index_name}).scalar()
        
        if check_index:
            op.drop_index(index_name, table_name=table)
        else:
            print(f"Index {index_name} on {table} does not exist, skipping drop.")
            
    # Helper to check if column exists
    check_column = connection.execute(sa.text(
        "SELECT 1 FROM information_schema.columns "
        "WHERE table_name = 'policies' AND column_name = 'reference_id'"
    )).scalar()
    
    if check_column:
        op.drop_column('policies', 'reference_id')
    else:
        print("Column reference_id on policies does not exist, skipping drop.")
    # ### end Alembic commands ###
