"""Add core governance entities

Revision ID: d0a202de9d67
Revises: 4116e4746a54
Create Date: 2026-05-22 15:26:14.663014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a202de9d67'
down_revision: Union[str, Sequence[str], None] = '4116e4746a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('reference_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_policies_reference_id'), 'policies', ['reference_id'], unique=False)
    op.create_index(op.f('ix_policies_status'), 'policies', ['status'], unique=False)
    op.create_index(op.f('ix_ai_models_status'), 'ai_models', ['status'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_ai_models_status'), table_name='ai_models')
    op.drop_index(op.f('ix_policies_status'), table_name='policies')
    op.drop_index(op.f('ix_policies_reference_id'), table_name='policies')
    op.drop_column('policies', 'reference_id')
    # ### end Alembic commands ###
