"""add workflow approver field

Revision ID: e716f1929aa1
Revises: b9148968854f
Create Date: 2026-06-07 10:42:21.219346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e716f1929aa1'
down_revision: Union[str, Sequence[str], None] = 'b9148968854f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('registry_relationships')]
    
    if 'purpose' in columns:
        op.drop_column('registry_relationships', 'purpose')
    if 'risk_level' in columns:
        op.drop_column('registry_relationships', 'risk_level')
    if 'permission_level' in columns:
        op.drop_column('registry_relationships', 'permission_level')
    if 'approval_requirement' in columns:
        op.drop_column('registry_relationships', 'approval_requirement')
    op.add_column('registry_workflows', sa.Column('approver_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'registry_workflows', 'guardian_users', ['approver_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('registry_workflows_approver_user_id_fkey', 'registry_workflows', type_='foreignkey')
    op.drop_column('registry_workflows', 'approver_user_id')
    op.add_column('registry_relationships', sa.Column('approval_requirement', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('registry_relationships', sa.Column('permission_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('registry_relationships', sa.Column('risk_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('registry_relationships', sa.Column('purpose', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
