"""phase_5_multi_layer_approval

Revision ID: ff5467dcb249
Revises: 5a10004_p5_rt
Create Date: 2026-08-22 01:37:21.401060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff5467dcb249'
down_revision: Union[str, Sequence[str], None] = '5a10004_p5_rt'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_owner_assignments',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('owner_group_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('version_no', sa.Integer(), server_default='1', nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.Column('metadata_json', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('(owner_user_id IS NOT NULL AND owner_group_id IS NULL) OR (owner_user_id IS NULL AND owner_group_id IS NOT NULL)', name='check_single_owner'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_group_id'], ['approval_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_approval_layer_selections',
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('layer_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('version_no', sa.Integer(), server_default='1', nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.Column('metadata_json', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['workflow_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('agent_data_permissions', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_agent_data_perms_lookup'), table_name='agent_data_permissions')
    op.create_index(op.f('ix_agent_data_permissions_agent_id'), 'agent_data_permissions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_data_permissions_data_source_id'), 'agent_data_permissions', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_agent_data_permissions_field_id'), 'agent_data_permissions', ['field_id'], unique=False)
    op.alter_column('agent_runtime_boundaries', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_tool_permissions', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_agent_tool_perms_lookup'), table_name='agent_tool_permissions')
    op.create_index(op.f('ix_agent_tool_permissions_agent_id'), 'agent_tool_permissions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_permissions_capability_id'), 'agent_tool_permissions', ['capability_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_permissions_tool_id'), 'agent_tool_permissions', ['tool_id'], unique=False)
    op.alter_column('agents', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_constraint(op.f('agents_owner_user_id_fkey'), 'agents', type_='foreignkey')
    op.create_foreign_key(None, 'agents', 'users', ['owner_user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_ai_models_status'), table_name='ai_models')
    op.drop_constraint(op.f('ai_models_owner_user_id_fkey'), 'ai_models', type_='foreignkey')
    op.create_foreign_key(None, 'ai_models', 'users', ['owner_user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('data_source_fields', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_data_source_fields_lookup'), table_name='data_source_fields')
    op.create_index(op.f('ix_data_source_fields_data_source_id'), 'data_source_fields', ['data_source_id'], unique=False)
    op.alter_column('data_sources', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_constraint(op.f('data_sources_owner_user_id_fkey'), 'data_sources', type_='foreignkey')
    op.create_foreign_key(None, 'data_sources', 'users', ['owner_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('departments', sa.Column('approval_default_order', sa.Integer(), nullable=True))
    op.alter_column('enforcement_decisions', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_enforcement_decisions_agent'), table_name='enforcement_decisions')
    op.create_index(op.f('ix_enforcement_decisions_agent_id'), 'enforcement_decisions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_enforcement_decisions_tool_id'), 'enforcement_decisions', ['tool_id'], unique=False)
    op.create_index(op.f('ix_enforcement_decisions_workflow_run_id'), 'enforcement_decisions', ['workflow_run_id'], unique=False)
    op.drop_index(op.f('idx_dead_letter_status'), table_name='event_dead_letter')
    op.drop_index(op.f('ix_event_dead_letter_tenant_status'), table_name='event_dead_letter')
    op.create_index(op.f('ix_event_dead_letter_tenant_id'), 'event_dead_letter', ['tenant_id'], unique=False)
    op.drop_index(op.f('idx_outbox_status_retry'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_status_next_retry'), table_name='event_outbox')
    op.drop_index(op.f('idx_processing_event_consumer'), table_name='event_processing_log')
    op.drop_constraint(op.f('uq_event_consumer'), 'event_processing_log', type_='unique')
    op.drop_constraint(op.f('uq_tenant_category_retention'), 'event_retention_rules', type_='unique')
    op.drop_constraint(op.f('uq_event_type_version'), 'event_schema_registry', type_='unique')
    op.drop_index(op.f('ix_composite_rel_lifecycle'), table_name='generic_relationships')
    op.drop_index(op.f('ix_composite_rel_source'), table_name='generic_relationships')
    op.drop_index(op.f('ix_composite_rel_target'), table_name='generic_relationships')
    op.drop_index(op.f('idx_events_actor_gin'), table_name='governance_events', postgresql_using='gin')
    op.drop_index(op.f('idx_events_category_time'), table_name='governance_events')
    op.drop_index(op.f('idx_events_correlation'), table_name='governance_events', postgresql_where='(correlation_id IS NOT NULL)')
    op.drop_index(op.f('idx_events_subject_gin'), table_name='governance_events', postgresql_using='gin')
    op.drop_index(op.f('idx_events_tenant_time'), table_name='governance_events')
    op.drop_index(op.f('idx_events_type_time'), table_name='governance_events')
    op.alter_column('governance_policies', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_gov_policies_effective'), table_name='governance_policies')
    op.drop_index(op.f('idx_gov_policies_tenant_status'), table_name='governance_policies')
    op.drop_index(op.f('ix_composite_resp_object'), table_name='object_responsibilities')
    op.alter_column('policy_approvals', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_policy_approvals_status_tier'), table_name='policy_approvals')
    op.create_index(op.f('ix_policy_approvals_evaluation_id'), 'policy_approvals', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_policy_approvals_policy_id'), 'policy_approvals', ['policy_id'], unique=False)
    op.drop_index(op.f('idx_policy_bindings_policy_status'), table_name='policy_bindings')
    op.drop_index(op.f('idx_policy_bindings_target_status'), table_name='policy_bindings')
    op.drop_index(op.f('ix_composite_pb_target'), table_name='policy_bindings')
    op.create_index(op.f('ix_policy_bindings_policy_id'), 'policy_bindings', ['policy_id'], unique=False)
    op.alter_column('policy_evaluations', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_policy_eval_lookup'), table_name='policy_evaluations')
    op.create_index(op.f('ix_policy_evaluations_causation_id'), 'policy_evaluations', ['causation_id'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_policy_id'), 'policy_evaluations', ['policy_id'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_target_id'), 'policy_evaluations', ['target_id'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_target_type'), 'policy_evaluations', ['target_type'], unique=False)
    op.alter_column('policy_exceptions', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_policy_exceptions_lookup'), table_name='policy_exceptions')
    op.create_index(op.f('ix_policy_exceptions_policy_id'), 'policy_exceptions', ['policy_id'], unique=False)
    op.create_index(op.f('ix_policy_exceptions_target_id'), 'policy_exceptions', ['target_id'], unique=False)
    op.create_index(op.f('ix_policy_exceptions_target_type'), 'policy_exceptions', ['target_type'], unique=False)
    op.alter_column('policy_rule_evaluations', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_policy_rule_eval_lookup'), table_name='policy_rule_evaluations')
    op.create_index(op.f('ix_policy_rule_evaluations_evaluation_id'), 'policy_rule_evaluations', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_policy_rule_evaluations_rule_id'), 'policy_rule_evaluations', ['rule_id'], unique=False)
    op.alter_column('policy_rules', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_policy_rules_target'), table_name='policy_rules')
    op.drop_index(op.f('idx_policy_rules_version'), table_name='policy_rules')
    op.create_index(op.f('ix_policy_rules_policy_version_id'), 'policy_rules', ['policy_version_id'], unique=False)
    op.create_index(op.f('ix_policy_rules_rule_code'), 'policy_rules', ['rule_code'], unique=False)
    op.alter_column('policy_versions', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_policy_versions_policy_num'), table_name='policy_versions')
    op.drop_index(op.f('idx_policy_versions_status'), table_name='policy_versions')
    op.create_index(op.f('ix_policy_versions_policy_id'), 'policy_versions', ['policy_id'], unique=False)
    op.alter_column('runtime_authorizations', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_runtime_authorizations_agent_id'), 'runtime_authorizations', ['agent_id'], unique=False)
    op.alter_column('runtime_enforcement_log', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_runtime_enforcement_log_agent_id'), 'runtime_enforcement_log', ['agent_id'], unique=False)
    op.create_index(op.f('ix_runtime_enforcement_log_causation_id'), 'runtime_enforcement_log', ['causation_id'], unique=False)
    op.create_index(op.f('ix_runtime_enforcement_log_tool_id'), 'runtime_enforcement_log', ['tool_id'], unique=False)
    op.alter_column('tool_capabilities', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_tool_capabilities_lookup'), table_name='tool_capabilities')
    op.create_index(op.f('ix_tool_capabilities_tool_id'), 'tool_capabilities', ['tool_id'], unique=False)
    op.alter_column('tools', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_constraint(op.f('tools_owner_user_id_fkey'), 'tools', type_='foreignkey')
    op.create_foreign_key(None, 'tools', 'users', ['owner_user_id'], ['id'], ondelete='SET NULL')
    # op.create_unique_constraint(None, 'users', ['email'])
    op.add_column('workflow_schedule_approvals', sa.Column('approval_cycle_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.add_column('workflow_schedule_approvals', sa.Column('approval_layer', sa.Integer(), server_default='1', nullable=False))
    op.add_column('workflow_schedule_approvals', sa.Column('parent_approval_id', sa.UUID(), nullable=True))
    op.add_column('workflow_schedule_approvals', sa.Column('department_id', sa.UUID(), nullable=True))
    op.add_column('workflow_schedule_approvals', sa.Column('skip_reason', sa.Text(), nullable=True))
    op.add_column('workflow_schedule_approvals', sa.Column('decided_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'workflow_schedule_approvals', 'users', ['decided_by'], ['id'])
    op.create_foreign_key(None, 'workflow_schedule_approvals', 'workflow_schedule_approvals', ['parent_approval_id'], ['id'])
    op.create_foreign_key(None, 'workflow_schedule_approvals', 'departments', ['department_id'], ['id'])
    op.drop_column('workflow_schedule_approvals', 'approver_group_id')
    op.alter_column('workflows', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_constraint(op.f('workflows_owner_user_id_fkey'), 'workflows', type_='foreignkey')
    op.create_foreign_key(None, 'workflows', 'users', ['owner_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.create_foreign_key(op.f('workflows_owner_user_id_fkey'), 'workflows', 'users', ['owner_user_id'], ['id'])
    op.alter_column('workflows', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.add_column('workflow_schedule_approvals', sa.Column('approver_group_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'workflow_schedule_approvals', type_='foreignkey')
    op.drop_constraint(None, 'workflow_schedule_approvals', type_='foreignkey')
    op.drop_constraint(None, 'workflow_schedule_approvals', type_='foreignkey')
    op.drop_column('workflow_schedule_approvals', 'decided_by')
    op.drop_column('workflow_schedule_approvals', 'skip_reason')
    op.drop_column('workflow_schedule_approvals', 'department_id')
    op.drop_column('workflow_schedule_approvals', 'parent_approval_id')
    op.drop_column('workflow_schedule_approvals', 'approval_layer')
    op.drop_column('workflow_schedule_approvals', 'approval_cycle_id')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'tools', type_='foreignkey')
    op.create_foreign_key(op.f('tools_owner_user_id_fkey'), 'tools', 'users', ['owner_user_id'], ['id'])
    op.alter_column('tools', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_index(op.f('ix_tool_capabilities_tool_id'), table_name='tool_capabilities')
    op.create_index(op.f('idx_tool_capabilities_lookup'), 'tool_capabilities', ['tool_id', 'capability_name'], unique=False)
    op.alter_column('tool_capabilities', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_runtime_enforcement_log_tool_id'), table_name='runtime_enforcement_log')
    op.drop_index(op.f('ix_runtime_enforcement_log_causation_id'), table_name='runtime_enforcement_log')
    op.drop_index(op.f('ix_runtime_enforcement_log_agent_id'), table_name='runtime_enforcement_log')
    op.alter_column('runtime_enforcement_log', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_runtime_authorizations_agent_id'), table_name='runtime_authorizations')
    op.alter_column('runtime_authorizations', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_policy_versions_policy_id'), table_name='policy_versions')
    op.create_index(op.f('idx_policy_versions_status'), 'policy_versions', ['policy_id', 'status'], unique=False)
    op.create_index(op.f('idx_policy_versions_policy_num'), 'policy_versions', ['policy_id', 'version_number'], unique=True)
    op.alter_column('policy_versions', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_policy_rules_rule_code'), table_name='policy_rules')
    op.drop_index(op.f('ix_policy_rules_policy_version_id'), table_name='policy_rules')
    op.create_index(op.f('idx_policy_rules_version'), 'policy_rules', ['policy_version_id', 'execution_order'], unique=False)
    op.create_index(op.f('idx_policy_rules_target'), 'policy_rules', ['target_type', 'target_id'], unique=False)
    op.alter_column('policy_rules', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_policy_rule_evaluations_rule_id'), table_name='policy_rule_evaluations')
    op.drop_index(op.f('ix_policy_rule_evaluations_evaluation_id'), table_name='policy_rule_evaluations')
    op.create_index(op.f('idx_policy_rule_eval_lookup'), 'policy_rule_evaluations', ['evaluation_id', 'rule_id'], unique=False)
    op.alter_column('policy_rule_evaluations', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_policy_exceptions_target_type'), table_name='policy_exceptions')
    op.drop_index(op.f('ix_policy_exceptions_target_id'), table_name='policy_exceptions')
    op.drop_index(op.f('ix_policy_exceptions_policy_id'), table_name='policy_exceptions')
    op.create_index(op.f('idx_policy_exceptions_lookup'), 'policy_exceptions', ['policy_id', 'target_type', 'target_id', 'status'], unique=False)
    op.alter_column('policy_exceptions', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_policy_evaluations_target_type'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_target_id'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_policy_id'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_causation_id'), table_name='policy_evaluations')
    op.create_index(op.f('idx_policy_eval_lookup'), 'policy_evaluations', ['policy_id', 'decision', 'created_at'], unique=False)
    op.alter_column('policy_evaluations', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_policy_bindings_policy_id'), table_name='policy_bindings')
    op.create_index(op.f('ix_composite_pb_target'), 'policy_bindings', ['tenant_id', 'target_type', 'target_id', 'status'], unique=False)
    op.create_index(op.f('idx_policy_bindings_target_status'), 'policy_bindings', ['target_type', 'target_id', 'status'], unique=False)
    op.create_index(op.f('idx_policy_bindings_policy_status'), 'policy_bindings', ['policy_id', 'status'], unique=False)
    op.drop_index(op.f('ix_policy_approvals_policy_id'), table_name='policy_approvals')
    op.drop_index(op.f('ix_policy_approvals_evaluation_id'), table_name='policy_approvals')
    op.create_index(op.f('idx_policy_approvals_status_tier'), 'policy_approvals', ['status', 'approval_tier'], unique=False)
    op.alter_column('policy_approvals', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_composite_resp_object'), 'object_responsibilities', ['tenant_id', 'object_type', 'object_id', 'responsibility_type', 'status'], unique=False)
    op.create_index(op.f('idx_gov_policies_tenant_status'), 'governance_policies', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('idx_gov_policies_effective'), 'governance_policies', ['effective_from', 'effective_to'], unique=False)
    op.alter_column('governance_policies', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('idx_events_type_time'), 'governance_events', ['event_type', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index(op.f('idx_events_tenant_time'), 'governance_events', ['tenant_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index(op.f('idx_events_subject_gin'), 'governance_events', ['subject_json'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_events_correlation'), 'governance_events', ['correlation_id'], unique=False, postgresql_where='(correlation_id IS NOT NULL)')
    op.create_index(op.f('idx_events_category_time'), 'governance_events', ['event_category', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index(op.f('idx_events_actor_gin'), 'governance_events', ['actor_json'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_composite_rel_target'), 'generic_relationships', ['tenant_id', 'target_type', 'target_id', 'relationship_type', 'status'], unique=False)
    op.create_index(op.f('ix_composite_rel_source'), 'generic_relationships', ['tenant_id', 'source_type', 'source_id', 'relationship_type', 'status'], unique=False)
    op.create_index(op.f('ix_composite_rel_lifecycle'), 'generic_relationships', ['tenant_id', 'status', 'effective_from', 'effective_to'], unique=False)
    op.create_unique_constraint(op.f('uq_event_type_version'), 'event_schema_registry', ['event_type', 'version'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_tenant_category_retention'), 'event_retention_rules', ['tenant_id', 'event_category'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_event_consumer'), 'event_processing_log', ['event_id', 'consumer_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_processing_event_consumer'), 'event_processing_log', ['event_id', 'consumer_id'], unique=False)
    op.create_index(op.f('ix_event_outbox_status_next_retry'), 'event_outbox', ['status', 'next_retry_at'], unique=False)
    op.create_index(op.f('idx_outbox_status_retry'), 'event_outbox', ['status', 'next_retry_at'], unique=False)
    op.drop_index(op.f('ix_event_dead_letter_tenant_id'), table_name='event_dead_letter')
    op.create_index(op.f('ix_event_dead_letter_tenant_status'), 'event_dead_letter', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('idx_dead_letter_status'), 'event_dead_letter', ['tenant_id', 'status'], unique=False)
    op.drop_index(op.f('ix_enforcement_decisions_workflow_run_id'), table_name='enforcement_decisions')
    op.drop_index(op.f('ix_enforcement_decisions_tool_id'), table_name='enforcement_decisions')
    op.drop_index(op.f('ix_enforcement_decisions_agent_id'), table_name='enforcement_decisions')
    op.create_index(op.f('idx_enforcement_decisions_agent'), 'enforcement_decisions', ['agent_id', 'enforced_at'], unique=False)
    op.alter_column('enforcement_decisions', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_column('departments', 'approval_default_order')
    op.drop_constraint(None, 'data_sources', type_='foreignkey')
    op.create_foreign_key(op.f('data_sources_owner_user_id_fkey'), 'data_sources', 'users', ['owner_user_id'], ['id'])
    op.alter_column('data_sources', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_index(op.f('ix_data_source_fields_data_source_id'), table_name='data_source_fields')
    op.create_index(op.f('idx_data_source_fields_lookup'), 'data_source_fields', ['data_source_id', 'field_name'], unique=False)
    op.alter_column('data_source_fields', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(None, 'ai_models', type_='foreignkey')
    op.create_foreign_key(op.f('ai_models_owner_user_id_fkey'), 'ai_models', 'users', ['owner_user_id'], ['id'])
    op.create_index(op.f('ix_ai_models_status'), 'ai_models', ['status'], unique=False)
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.create_foreign_key(op.f('agents_owner_user_id_fkey'), 'agents', 'users', ['owner_user_id'], ['id'])
    op.alter_column('agents', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_index(op.f('ix_agent_tool_permissions_tool_id'), table_name='agent_tool_permissions')
    op.drop_index(op.f('ix_agent_tool_permissions_capability_id'), table_name='agent_tool_permissions')
    op.drop_index(op.f('ix_agent_tool_permissions_agent_id'), table_name='agent_tool_permissions')
    op.create_index(op.f('idx_agent_tool_perms_lookup'), 'agent_tool_permissions', ['agent_id', 'tool_id', 'is_active'], unique=False)
    op.alter_column('agent_tool_permissions', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_runtime_boundaries', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_agent_data_permissions_field_id'), table_name='agent_data_permissions')
    op.drop_index(op.f('ix_agent_data_permissions_data_source_id'), table_name='agent_data_permissions')
    op.drop_index(op.f('ix_agent_data_permissions_agent_id'), table_name='agent_data_permissions')
    op.create_index(op.f('idx_agent_data_perms_lookup'), 'agent_data_permissions', ['agent_id', 'data_source_id', 'is_active'], unique=False)
    op.alter_column('agent_data_permissions', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_table('schedule_approval_layer_selections')
    op.drop_table('department_owner_assignments')
    # ### end Alembic commands ###
