class ErrorCodes:
    VALIDATION_ERROR = "VALIDATION_ERROR"

    UNAUTHORIZED = "UNAUTHORIZED"

    FORBIDDEN = "FORBIDDEN"

    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"

    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    