from enum import Enum

class AuditEventType(str, Enum):
    CREATED = "CREATED"
    UPDATED = "UPDATED"
    POLICY_TRIGGERED = "POLICY_TRIGGERED"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    ESCALATED = "ESCALATED"
    ACTION_EXECUTED = "ACTION_EXECUTED"
    SLA_BREACHED = "SLA_BREACHED"
    POLICY_VIOLATION = "POLICY_VIOLATION"
