from enum import Enum

class ExecutionMode(str, Enum):
    READ_ONLY = "READ_ONLY"
    RECOMMEND_ONLY = "RECOMMEND_ONLY"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    LIMITED_EXECUTION = "LIMITED_EXECUTION"
    FULLY_BLOCKED = "FULLY_BLOCKED"
