from enum import Enum

class RelationshipType(str, Enum):
    OWNED_BY = "OWNED_BY"
    REVIEWED_BY = "REVIEWED_BY"
    APPROVED_BY = "APPROVED_BY"
    EXECUTED_BY = "EXECUTED_BY"
    USES_MODEL = "USES_MODEL"
    USES_TOOL = "USES_TOOL"
    USES_DATA_SOURCE = "USES_DATA_SOURCE"
    PARTICIPATES_IN_WORKFLOW = "PARTICIPATES_IN_WORKFLOW"
    GOVERNED_BY = "GOVERNED_BY"
    EVALUATED_BY = "EVALUATED_BY"
    SUPPORTED_BY = "SUPPORTED_BY"
    RESULTS_IN = "RESULTS_IN"
    TRIGGERS = "TRIGGERS"
    ESCALATED_TO = "ESCALATED_TO"
    DELEGATED_TO = "DELEGATED_TO"
    BELONGS_TO = "BELONGS_TO"
    MEMBER_OF = "MEMBER_OF"
    HAS_PERMISSION = "HAS_PERMISSION"
    VIOLATES = "VIOLATES"
    REMEDIATED_BY = "REMEDIATED_BY"


class LifecycleState(str, Enum):
    PROPOSED = "PROPOSED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    REVOKED = "REVOKED"
    EXPIRED = "EXPIRED"
    ARCHIVED = "ARCHIVED"
    REJECTED = "REJECTED"


class ResponsibilityType(str, Enum):
    OWNER = "OWNER"
    REVIEWER = "REVIEWER"
    APPROVER = "APPROVER"
    EXECUTOR = "EXECUTOR"
    AUDITOR = "AUDITOR"
    ESCALATION_OWNER = "ESCALATION_OWNER"


class ValidationRuleCategory(str, Enum):
    OWNERSHIP = "OWNERSHIP"
    DUPLICATE = "DUPLICATE"
    TEMPORAL = "TEMPORAL"
    LIFECYCLE = "LIFECYCLE"
    CROSS_TENANT = "CROSS_TENANT"
    GRAPH_INTEGRITY = "GRAPH_INTEGRITY"
